export interface DTOXlsxPreview {
    idliq: number,
    plataforma: string,
    liquidacion: string,
    codigodeentrega: string,
    fechaprevista: string,
    codsap: string,
    brevedescripcion: string,
    qty: number,
    um: string,
    serieorgen: string,
    seriefinal: string,
    trabajorealizado: string,
    estado: string,
    componentes: string,
    costounitario: number,
    costototal: number,
    motivoentrega: string,
    guiaingreso: string,
    guiasalida: string,
    status_sap: string,
    ordendecompra:string ,
    contabilizado:string ,
    pedido:string ,
    reingreso: number
}
